import type { HookMeta } from "@/types";

export const CATEGORIES = [
  "Git Safety",
  "Code Quality",
  "Security",
  "Notifications",
  "Context Management",
  "Workflow Automation",
  "Environment",
  "Permissions",
  "Observability",
  "Agent Teams",
] as const;

export const HOOKS: HookMeta[] = [
  // Git Safety
  {
    name: "gitguard",
    displayName: "Git Guard",
    description: "Blocks destructive git operations like reset --hard, push --force, clean -f",
    version: "0.1.0",
    category: "Git Safety",
    event: "PreToolUse",
    matcher: "Bash",
    tags: ["git", "safety", "destructive", "guard"],
  },
  {
    name: "branchprotect",
    displayName: "Branch Protect",
    description: "Prevents editing files directly on main/master branch",
    version: "0.1.0",
    category: "Git Safety",
    event: "PreToolUse",
    matcher: "Write|Edit|NotebookEdit",
    tags: ["git", "branch", "protection", "main"],
  },
  {
    name: "checkpoint",
    displayName: "Checkpoint",
    description: "Creates shadow git snapshots before file modifications for easy rollback",
    version: "0.1.0",
    category: "Git Safety",
    event: "PreToolUse",
    matcher: "Write|Edit|NotebookEdit",
    tags: ["git", "snapshot", "rollback", "backup"],
  },

  // Code Quality
  {
    name: "checktests",
    displayName: "Check Tests",
    description: "Checks for missing tests after file edits",
    version: "0.1.6",
    category: "Code Quality",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["tests", "coverage", "quality"],
  },
  {
    name: "checklint",
    displayName: "Check Lint",
    description: "Runs linting after file edits and creates tasks for errors",
    version: "0.1.7",
    category: "Code Quality",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["lint", "style", "quality"],
  },
  {
    name: "checkfiles",
    displayName: "Check Files",
    description: "Runs headless agent to review files and create tasks",
    version: "0.1.4",
    category: "Code Quality",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["review", "files", "quality"],
  },
  {
    name: "checkbugs",
    displayName: "Check Bugs",
    description: "Checks for bugs via headless agent",
    version: "0.1.6",
    category: "Code Quality",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["bugs", "analysis", "quality"],
  },
  {
    name: "checkdocs",
    displayName: "Check Docs",
    description: "Checks for missing documentation and creates tasks",
    version: "0.2.1",
    category: "Code Quality",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["docs", "documentation", "quality"],
  },
  {
    name: "checktasks",
    displayName: "Check Tasks",
    description: "Validates task completion and tracks progress",
    version: "1.0.8",
    category: "Code Quality",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["tasks", "tracking", "quality"],
  },

  // Security
  {
    name: "checksecurity",
    displayName: "Check Security",
    description: "Runs security checks via headless agents",
    version: "0.1.6",
    category: "Security",
    event: "PostToolUse",
    matcher: "Edit|Write|NotebookEdit",
    tags: ["security", "audit", "vulnerabilities"],
  },
  {
    name: "packageage",
    displayName: "Package Age",
    description: "Checks package age before install to prevent typosquatting",
    version: "0.1.1",
    category: "Security",
    event: "PreToolUse",
    matcher: "Bash",
    tags: ["npm", "packages", "typosquatting", "supply-chain"],
  },

  // Notifications
  {
    name: "phonenotify",
    displayName: "Phone Notify",
    description: "Sends push notifications to phone via ntfy.sh",
    version: "0.1.0",
    category: "Notifications",
    event: "Stop",
    matcher: "",
    tags: ["notification", "phone", "push", "ntfy"],
  },
  {
    name: "agentmessages",
    displayName: "Agent Messages",
    description: "Inter-agent messaging integration for service-message",
    version: "0.1.0",
    category: "Notifications",
    event: "Stop",
    matcher: "",
    tags: ["messaging", "agents", "inter-agent"],
  },
  {
    name: "desktopnotify",
    displayName: "Desktop Notify",
    description: "Sends native desktop notifications via osascript (macOS) or notify-send (Linux)",
    version: "0.1.0",
    category: "Notifications",
    event: "Stop",
    matcher: "",
    tags: ["notification", "desktop", "macos", "linux", "native"],
  },
  {
    name: "slacknotify",
    displayName: "Slack Notify",
    description: "Sends Slack webhook notifications when Claude finishes",
    version: "0.1.0",
    category: "Notifications",
    event: "Stop",
    matcher: "",
    tags: ["notification", "slack", "webhook", "team"],
  },
  {
    name: "soundnotify",
    displayName: "Sound Notify",
    description: "Plays a system sound when Claude finishes (macOS/Linux)",
    version: "0.1.0",
    category: "Notifications",
    event: "Stop",
    matcher: "",
    tags: ["notification", "sound", "audio", "alert"],
  },

  // Context Management
  {
    name: "contextrefresh",
    displayName: "Context Refresh",
    description: "Re-injects important context every N prompts to prevent drift",
    version: "0.1.0",
    category: "Context Management",
    event: "Notification",
    matcher: "",
    tags: ["context", "memory", "prompts", "refresh"],
  },
  {
    name: "precompact",
    displayName: "Pre-Compact",
    description: "Saves session state before context compaction",
    version: "0.1.0",
    category: "Context Management",
    event: "Notification",
    matcher: "",
    tags: ["context", "compaction", "state", "backup"],
  },

  // Workflow Automation
  {
    name: "autoformat",
    displayName: "Auto Format",
    description: "Runs project formatter (Prettier, Biome, Ruff, Black, gofmt) after file edits",
    version: "0.1.0",
    category: "Workflow Automation",
    event: "PostToolUse",
    matcher: "Edit|Write",
    tags: ["format", "prettier", "biome", "ruff", "black", "gofmt", "style"],
  },
  {
    name: "autostage",
    displayName: "Auto Stage",
    description: "Automatically git-stages files after Claude edits them",
    version: "0.1.0",
    category: "Workflow Automation",
    event: "PostToolUse",
    matcher: "Edit|Write",
    tags: ["git", "stage", "add", "auto"],
  },
  {
    name: "tddguard",
    displayName: "TDD Guard",
    description: "Blocks implementation edits unless corresponding test files exist",
    version: "0.1.0",
    category: "Workflow Automation",
    event: "PreToolUse",
    matcher: "Edit|Write",
    tags: ["tdd", "tests", "red-green-refactor", "enforcement"],
  },

  // Environment
  {
    name: "envsetup",
    displayName: "Env Setup",
    description: "Warns when nvm, virtualenv, asdf, or rbenv may need activation before commands",
    version: "0.1.0",
    category: "Environment",
    event: "PreToolUse",
    matcher: "Bash",
    tags: ["nvm", "virtualenv", "asdf", "rbenv", "environment", "python", "node"],
  },

  // Permissions
  {
    name: "permissionguard",
    displayName: "Permission Guard",
    description: "Auto-approves safe read-only commands and blocks dangerous operations",
    version: "0.1.0",
    category: "Permissions",
    event: "PreToolUse",
    matcher: "Bash",
    tags: ["permission", "allowlist", "blocklist", "safety", "auto-approve"],
  },
  {
    name: "protectfiles",
    displayName: "Protect Files",
    description: "Blocks access to .env, secrets, SSH keys, and lock files",
    version: "0.1.0",
    category: "Permissions",
    event: "PreToolUse",
    matcher: "Edit|Write|Read|Bash",
    tags: ["security", "env", "secrets", "keys", "lock-files", "protect"],
  },
  {
    name: "promptguard",
    displayName: "Prompt Guard",
    description: "Blocks prompt injection attempts and credential access requests",
    version: "0.1.0",
    category: "Permissions",
    event: "PreToolUse",
    matcher: "",
    tags: ["prompt", "injection", "security", "validation", "guard"],
  },

  // Observability
  {
    name: "sessionlog",
    displayName: "Session Log",
    description: "Logs every tool call to .claude/session-log-<date>.jsonl",
    version: "0.1.0",
    category: "Observability",
    event: "PostToolUse",
    matcher: "",
    tags: ["logging", "audit", "session", "history", "jsonl"],
  },
  {
    name: "commandlog",
    displayName: "Command Log",
    description: "Logs every bash command Claude runs to .claude/commands.log",
    version: "0.1.0",
    category: "Observability",
    event: "PostToolUse",
    matcher: "Bash",
    tags: ["logging", "bash", "commands", "audit"],
  },
  {
    name: "costwatch",
    displayName: "Cost Watch",
    description: "Estimates session token usage and warns when budget threshold is exceeded",
    version: "0.1.0",
    category: "Observability",
    event: "Stop",
    matcher: "",
    tags: ["cost", "tokens", "budget", "usage", "monitoring"],
  },
  {
    name: "errornotify",
    displayName: "Error Notify",
    description: "Detects tool failures and logs errors to .claude/errors.log",
    version: "0.1.0",
    category: "Observability",
    event: "PostToolUse",
    matcher: "",
    tags: ["errors", "failures", "logging", "debugging"],
  },

  // Agent Teams
  {
    name: "taskgate",
    displayName: "Task Gate",
    description: "Validates task completion criteria before allowing tasks to be marked done",
    version: "0.1.0",
    category: "Agent Teams",
    event: "PostToolUse",
    matcher: "",
    tags: ["tasks", "completion", "gate", "quality", "agent-teams"],
  },
];
